
POST http://localhost:3000/courses
Content-Type: application/json

{
    "title": "Curs"
}

##############

GET http://localhost:3000/courses

##############

GET http://localhost:3000/courses/58a72731-2052-4e7f-bff1-9d56e76d7076

#############

